version: '3.8'

services:
  frontend-dev:
    image: node:20-alpine
    container_name: patitasfelices-frontend-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    networks:
      - frontend-network
    environment:
      - CHOKIDAR_USEPOLLING=true    # Ayuda a detectar cambios en archivos
    command: sh -c "npm install && npm run dev -- --host"

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patitasfelices-frontend-prod
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=/backend # O la URL de tu backend en producción
    networks:
      - frontend-network

networks:
  frontend-network:
    external: true
    name: patitasfelices-network

